### ISSUE TITLE
style suggestions

### ISSUE THREAD

**Issue by kaczmarj** [johnjmurray/AEM594#1]
hi john -- cool repo. i had some python style suggests. they are all nitpicky but i wanted to share anyway.

it's great that you're adding documentation to your functions. that's really important, because future you won't remember why you wrote things the way you did. instead of comments, though, you should use triple-quote strings.

so instead of 

```python
def foobar(foo):
    # Inputs: foo
    # Outputs: bar
```

i would write something like

```python
def foobar(foo):
    """Calculates the foo of bar.

    Inputs: foo
    Outputs: bar
    """
```

when you put it in quotes instead of as comments, you can access the text using `help(foobar)` or `foobar.__doc__`. you can't do that with comments.

this is getting very pedantic, but there are lots of different styles on "docstrings" (the triple-quoted strings at the beginning of functions). i like numpy-style (https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard), but projects like tensorflow use a different style. in my opinion, the style doesn't really matter as long as you're getting across the important information.

another pedantic comment i wanted to make is that typically you use "snake-case" for things in python, and you use camel-case for class names. it doesn't really matter, but that's what most people do.

now i'm lying here in bed wondering whether i am a pedant and whether i should delete this comment entirely. i won't, of course.

**Comment by johnjmurray** [comment]
Jakub,

Thank you so much for the comments! I feel Seen, and appreciate that you would spend time looking at this. I will take your suggestions of course. I am always asking for style help -- please feel free to comment away on anything I write.

Besos,

John
